# -*- coding: utf-8 -*-
"""Tarmin_python_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mE-qU141oNSEbZM0R0YxB6UAK9S4NDK
"""

# Mount the Google Drive

import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

# Import csv file using pandas in a dataframe (e.g df_employee)

Google_drive_path = '/content/drive/MyDrive/Python classes/Python project/'
assert Google_drive_path is not None
Google_Drive_Path_Final = os.path.join('drive','MyDrive', Google_drive_path)

df_employee = pd.read_csv(os.path.join(Google_drive_path, 'Employee_Details.csv'))
df_employee

# Import csv file using pandas in a dataframe (e.g df_health)

Google_drive_path = '/content/drive/MyDrive/Python classes/Python project/'
assert Google_drive_path is not None
Google_Drive_Path_Final = os.path.join('drive','MyDrive', Google_drive_path)

df_health = pd.read_csv(os.path.join(Google_drive_path, 'Employee_Health.csv'))
df_health

# Remove duplicate rows (if any)
df_employee = df_employee.drop_duplicates()
df_employee

# Remove duplicate rows (if any)
df_health = df_health.drop_duplicates()
df_health

# Clean special characters in the ‘Name’ column
df_employee['Name'] = df_employee['Name'].str.strip('/123._')
df_employee['Name']

# Clean special characters in the ‘Name’ column
df_health['Name'] = df_health['Name'].str.strip('/123._')
df_health['Name']

# Make numeric values 0 and 1 for Smoking column
df_health['SmokingStatus'] = df_health['SmokingStatus'].replace({'Smoker':1, 'Non-Smoker':0})
df_health

# Split date and time for ‘last_login’ column

df_employee[['LastLogin_Date', 'LastLogin_Time']] = df_employee['LastLogin'].str.split(' ', expand=True)
df_employee

df_employee = df_employee.drop(columns=['LastLogin'])
df_employee

# Make all department-names same case (upper or lower)

df_employee['Department'] = df_employee['Department'].str.upper()

df_employee['Department']

# Make all department-names same case (upper or lower)

df_health['Department'] = df_health['Department'].str.upper()

df_health['Department']

# Replace all null department-names with ‘Unknown department’

df_employee['Department'] = df_employee['Department'].fillna('UNKNOWN DEPARTMENT')
df_employee['Department']

# Replace all null department-names with ‘Unknown department’

df_health['Department'] = df_health['Department'].fillna('UNKNOWN DEPARTMENT')
df_health['Department']

# Calculate the average/mean age of employees

import numpy as np

mean_age = np.mean(df_employee['Age'])

# Round to 2 decimal places
mean_age_rounded = round(mean_age, 2)

print('Average Age of Employees:', mean_age_rounded)

# Calculate the mean stress level of employees

mean_StressLevel = np.mean(df_health['StressLevel'])

# Round to 2 decimal places
mean_StressLevel_rounded = round(mean_StressLevel, 2)

print('Average Stress level of employees:', mean_StressLevel_rounded)

# Calculate the median of work hours

median_workhours = np.median(df_health['WorkHours'].dropna())

print('Median of work hours:', median_workhours)

# Calculate the mininum sleep hours

min_sleephours = np.min(df_health['SleepHours'].dropna())

print('Minimum sleep hours:', min_sleephours)

# Calculate the maximum of step count

max_stepcount = np.max(df_health['StepCount'].dropna())

print('Maximum step count:', max_stepcount)

# Merge the dataframes (outer) on primary-key

df_merge_outer = pd.merge(df_employee, df_health, on='EmployeeID', how='outer')
df_merge_outer

# Merge the dataframes (inner) on primary-key

df_merge_inner = pd.merge(df_employee, df_health, on='EmployeeID', how='inner')
df_merge_inner

# Group by Departments on employees' mean age (average age)

df_grouped_department = df_merge_inner.groupby('Department_x').agg(Mean_Age=('Age', 'mean')).round(2).sort_values(by='Mean_Age')
df_grouped_department

# Group by Departments on employees’ Mean Productivity score

df_grouped_dept = df_merge_inner.groupby('Department_x').agg(Mean_ProductivityScore=('ProductivityScore' , 'mean')).round(2).sort_values(by='Mean_ProductivityScore')
df_grouped_dept

# Order by Productivity score (Descending order)

df_sorted = df_merge_inner.sort_values(by='ProductivityScore', ascending=False)
df_sorted

# Employee count on each department

df_grouped_count = df_employee.groupby('Department').agg(Employee_Count=('EmployeeID', 'count')).sort_values(by='Employee_Count')
df_grouped_count

# Horizontal bar-chart of employee distribution across different departments

import matplotlib.pyplot as plt

df_grouped_count.plot(kind = 'barh', title = 'Employee Distribution Across Departments', xlabel = 'Employee_Count', ylabel = 'Department',
                      figsize=(10, 6), color= 'steelblue', legend=False)

# Title fontsize
plt.title('Employee Distribution Across Departments', fontsize=14)

# Axis label fontsize
plt.xlabel('Employee Count', fontsize=12)
plt.ylabel('Department', fontsize=12)

# Add count labels on each bar
for index, value in enumerate(df_grouped_count['Employee_Count']):
    plt.text(value, index, str(value), va='center', fontsize=10)

# Prevents labels getting cut off
plt.tight_layout()

# Display the chart
plt.show()

# Cleaning of gender column in df_employee

df_employee['Gender']=df_employee['Gender'].replace({'Mle':'Male', 'Fmale':'Female'})
df_employee['Gender']

# Employee count for each gender
df_grouped_gender = df_employee.groupby('Gender').agg(Employee_Count=('EmployeeID', 'count')).sort_values(by='Employee_Count')
df_grouped_gender

#	Bar chart group by gender count

import matplotlib.pyplot as plt

df_grouped_gender.plot(kind = 'bar', title = 'Employee Count By Gender', xlabel = 'Gender', ylabel = 'Employee_Count',
                      figsize=(8, 5), color= 'orange', legend=False)

# Title fontsize
plt.title('Employee Count By Gender', fontsize=14)

# Axis label fontsize
plt.xlabel('Gender', fontsize=12)
plt.ylabel('Employee Count', fontsize=12)

# Add count labels on each bar
for index, value in enumerate(df_grouped_gender['Employee_Count']):
    plt.text(index, value, str(value), ha='center', fontsize=10)

# Prevents labels getting cut off
plt.tight_layout()

# keeps Gender labels horizontal
plt.xticks(rotation=0)

# Display the chart
plt.show()

# Cleaning of gender column in df_health

df_health['Gender']=df_health['Gender'].replace({'Mle':'Male', 'Fmale':'Female'})
df_health['Gender']

# Average stresslevel for each gender

df_grouped_avg = df_health.groupby('Gender').agg(Average_StressLevel=('StressLevel','mean')).round(2).sort_values(by='Average_StressLevel')
df_grouped_avg

# Bar chart on merged_df Group by gender on average StressLevel

df_grouped_avg.plot(kind = 'bar', title = 'Average Stress Level By Gender', xlabel = 'Gender', ylabel = 'Average_StressLevel',
                      figsize=(8, 5), color= 'green', legend=False)

# Title fontsize
plt.title('Average Stress Level By Gender', fontsize=14)

# Axis label fontsize
plt.xlabel('Gender', fontsize=12)
plt.ylabel('Average Stress Level', fontsize=12)

# Add count labels on each bar
for index, value in enumerate(df_grouped_avg['Average_StressLevel']):
    plt.text(index, value, str(value), ha='center', fontsize=10)

# Prevents labels getting cut off
plt.tight_layout()

# keeps Gender labels horizontal
plt.xticks(rotation=0)

# Display the chart
plt.show()

# Scatter Plot of Work Hours vs Productivity Score

df_health.plot(kind='scatter',x='WorkHours', y = 'ProductivityScore', title = 'Productivity Score vs Work Hours', xlabel='Work Hours',
               ylabel='Productivity Score', figsize=(10, 6), color='red',alpha=0.6)

plt.tight_layout()
plt.show()

# ADD Correlation Score
correlation = df_health['WorkHours'].corr(df_health['ProductivityScore'])
print(f'Correlation between ProductivityScore and WorkHours: {round(correlation, 2)}')

# Line chart for employee-name vs last_login_date

# Step 1 — Convert to datetime
df_employee['LastLogin_Date'] = pd.to_datetime(df_employee['LastLogin_Date'])

# Step 2 — Make login_trend variable
login_trend = df_employee.set_index('Name')['LastLogin_Date']

# Step 3 — Plot
login_trend.plot(kind='line',title='Employee Last Login Activity Trend',xlabel='Employee Name',ylabel='Last Login Date',figsize=(20, 6),color='blue',
                 linewidth=0.08,legend=False)

plt.title('Employee Last Login Activity Trend', fontsize=20)
plt.xlabel('Employee Name', fontsize=15)
plt.ylabel('Last Login Date', fontsize=15)
plt.grid(True)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()